import type { Metadata } from "next";
import "@/public/globals.css";
import { LocaleProvider } from "@/app/components/contexts/LocalContextProvider";
import { MapProvider } from "@/app/components/contexts/MapContextProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <LocaleProvider>
            <MapProvider>
                <html lang="en">
                    <body>{children}</body>
                </html>
            </MapProvider>
        </LocaleProvider>
    );
}
