import type { Metadata } from "next";
import "@/public/globals.css";
import { LocaleProvider } from "@/app/providers/LocalContextProvider";
import { MapProvider } from "@/app/providers/MapContextProvider";
import { AdminMapConfigProvider } from "@/app/providers/AdminMapConfigContextProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <LocaleProvider>
            <AdminMapConfigProvider>
                <MapProvider>
                    <html lang="en">
                        <body>{children}</body>
                    </html>
                </MapProvider>
            </AdminMapConfigProvider>
        </LocaleProvider>
    );
}
