import type { Metadata } from "next";
import "@/public/globals.css";
import { LocaleProvider } from "../providers/LocalContextProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <LocaleProvider>{children}</LocaleProvider>
            </body>
        </html>
    );
}
